### ISSUE TITLE
Release weights for pretrained NTC model, NTSCC+ with other lmbdas, and compatible NTSCC+

### ISSUE THREAD

**Issue by asdLeaving** [wsxtyrdd/NTSCC_plus#3]
I'm trying to modify the structure of adaptive modules introduced by compatible NTSCC+, to make the compatible single model perform more closely to the individual NTSCC+ models.
Please release **weights** for 
1. **pretrained NTC model**, which is essential for training any model based on NTSCC+ and later architecture.
2. **NTSCC+ with other lmbdas**, which is essential for evaluate the performance gap between the original model and the compatible model.
3. **compatible NTSCC+**, which is used for comparing the modified network and the original compatible NTSCC+.

If the weights are difficult to upload, please **release the testing results** used to plot the PSNR vs CBR/SNR curves in the paper, like how CompressAI releases the testing results in numbers.
Also, the **code for compatible NTSCC+** is also helpful, since its implementation details (e.g. number of hidden units of FCN, how datapoints used to interpolate c_{global,ν} is implemented) are missing in the paper.

**Comment by wsxtyrdd** [comment]
Thank you for your interest in our work. I have now uploaded more pretrained weights, including pretrained NTC weights, more NTSCC+ weights, and compatible NTSCC+ weights. Please check the Google Drive link provided. Feel free to explore the code and experiment with the models.
